### ISSUE TITLE
Codelab instructions order

### ISSUE THREAD

**Issue by danybony** [greenido/bitcoin-info-action#2]
Hello there, 
I presented this project as a codelab at DevFest1 Veneto, the 2nd of December 2017.
See https://codelabs.developers.google.com/codelabs/your-first-action-on-google-with-webhook
While preparing the codelab I found these issues with the steps:
- End conversation checkbox described in step 3 but only available after enabling "Google Assistant" integration in step 4.
- The web demo page, described at the end of step 4, needs to be enabled in the integrations to be available (not specified in the step).

**Comment by greenido** [comment]
Thank you! I'll work on it during 2018 👍

**Comment by greenido** [comment]
I've fixed the 2 points - thank you!
