### ISSUE TITLE
Does the live API still work?

### ISSUE THREAD

**Issue by RayBB** [greenido/bitcoin-info-action#6]
I imported the zip into dialog flow and when I test it I get the response "I'm sorry but I can't find the price right now."

I'm getting the error `Webhook call failed. Error: 400 Bad Request`

Perhaps the webhook (https://us-central1-bitcoin-info-io17.cloudfunctions.net/bitcoinInfo) is no longer working properly or am I doing something wrong?

**Comment by greenido** [comment]
Thank you - But I'm no longer with Google and my hunch is that someone 'shutdown' this demo...
